### ISSUE TITLE
Bootstrap the server more cleanly

### ISSUE THREAD

**Issue by moreirathomas** [benchttp/server#14]
## Description

Improve the bootstrap of the server for better configuration/logging/monitoring.

## Tasks

- [x] break down `main`
- [x] inject env variables more cleanly
- [x] defer close of `firebase.Client` (see https://github.com/benchttp/server/pull/13#discussion_r815914538)

And more?
